// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3EKYq_J2p8aH7f9rznqrwTQgvmbKeM2E',
    appId: '1:154292031253:web:cddadbb0edc60af11c231c',
    messagingSenderId: '154292031253',
    projectId: 'driver-app-63d46',
    authDomain: 'driver-app-63d46.firebaseapp.com',
    databaseURL: 'https://driver-app-63d46-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'driver-app-63d46.firebasestorage.app',
    measurementId: 'G-XWDDXEHNRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGJkM_bV72VNjKmYSTtYSLqUua4B2YJKw',
    appId: '1:154292031253:android:4421348a62d19bd61c231c',
    messagingSenderId: '154292031253',
    projectId: 'driver-app-63d46',
    databaseURL: 'https://driver-app-63d46-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'driver-app-63d46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQXJxDxYZCT__3z5dCs7Jv3rlfYnsNCGc',
    appId: '1:154292031253:ios:9149a3bb6fff06861c231c',
    messagingSenderId: '154292031253',
    projectId: 'driver-app-63d46',
    databaseURL: 'https://driver-app-63d46-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'driver-app-63d46.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );
}
